apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aspnetcore
        version: v1
    spec:
      containers:
      - name: aspnetcore
        image: shreemada/helloworldaspnetcore:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080