apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-v1
spec:
  replicas: 3
  selector:
    matchLabels:
     app: aspnetcore
  template:
    metadata:
      labels:
        app: aspnetcore
        version: v1
    spec:
      containers:
      - name: aspnetcore
        image: gcr.io/aspnetcore-305011/aspnetcore:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
